# Generated by Django 3.1.3 on 2020-11-16 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.AddField(
            model_name='item',
            name='takuhaikenpin',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='宅配検品'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(choices=[('高橋悠人', '高橋悠人'), ('足立雄介', '足立雄介'), ('井上貴子', '井上貴子'), ('柿崎義弘', '柿崎義弘'), ('斎藤祐樹', '斎藤祐樹'), ('和田昭雄', '和田昭雄')], max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, 'テスト')], default=1, verbose_name='性別'),
        ),
    ]
